### ISSUE TITLE
Recomendación

### ISSUE THREAD

**Issue by Theby** [marcialhernandez/Lab3MPI#1]
Usa C++, acá hay una guía bkn ;) http://lsi.ugr.es/jmantas/pdp/ayuda/mpi_ayuda.php?ayuda=MPI_Init

puedes ponerle el namespace MPI; para hacer más fácil la escritura, a mi me funcionó impequé, mi código es como de 50 líneas xd

**Comment by marcialhernandez** [comment]
Muchas gracias!!
